About bakksy block
Katiasun/Landing-Pages pull request #9
Opened 2023-04-22 10:13 UTC by Katiasun

2023-05-08 20:08 UTC, Katiasun commented on src/components/AboutBakksyBlock/index.jsx
> +          <img
I change this (img)

2023-05-09 07:36 UTC, Todmy requested changes

2023-05-09 07:36 UTC, Todmy commented on src/components/AboutBakksyBlock/styles.module.css
> +/* .btnInvestment img {
do you need this comment?

2023-05-09 14:13 UTC, Katiasun commented on src/components/AboutBakksyBlock/styles.module.css
> +/* .btnInvestment img {
fix this, deleted

2023-05-09 14:14 UTC, Todmy approved these changes

2023-05-09 14:15 UTC, merged